[project]
name = "spike-documents"
version = "0.1.0"
dependencies = [
    "prefect>=3.4.3",
 "pydantic>=2.11.4",
 "pytest>=8.3.5",
]

[tool.pyright]
include = ["**/*"]

[dependency-groups]
dev = ["basedpyright>=1.29.2"]
